import { Crop } from '../types';

export const BENCHMARK_CROPS: Crop[] = [
  {
    cropIndex: 1,
    productName: 'PAPA TARDIA',
    yieldUnit: 'CARGA',
    cyclesPerYear: 1,
    cultivatedAreaHectares: 1,
    harvestWasteOrConsumption: 1,
    yieldPerHectare: 145,
    totalYield: 144,
    salePrice: 250,
    totalProductionCost: 21252,
    totalSales: 36000,
    grossMarginPercentage: 0.4097,
    salesMonthlyDistribution: [0.30, 0.70, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    costsMonthlyDistribution: [0, 0, 0.20, 0.60, 0.20, 0, 0, 0, 0, 0, 0, 0],
    costItems: [
      { itemIndex: 1, activityName: 'Preparacion del Terreno', costCategory: 'Mantenimiento', quantity: 4, unit: 'HORA', unitCost: 150, totalCost: 600 },
      { itemIndex: 2, activityName: 'Siembra', costCategory: 'Siembra', quantity: 10, unit: 'JORNAL', unitCost: 100, totalCost: 1000 },
      { itemIndex: 3, activityName: 'Semilla', costCategory: 'Insumos', quantity: 20, unit: 'CARGA', unitCost: 450, totalCost: 9000 },
      { itemIndex: 4, activityName: 'Abono Quimico', costCategory: 'Insumos', quantity: 6, unit: 'QUINTAL', unitCost: 350, totalCost: 2100 },
      { itemIndex: 5, activityName: 'Abono Organico', costCategory: 'Insumos', quantity: 1, unit: 'CAMION', unitCost: 3500, totalCost: 3500 },
      { itemIndex: 6, activityName: 'Remedios Quimicos', costCategory: 'Labores Culturales', quantity: 4, unit: 'LITRO', unitCost: 350, totalCost: 1400 },
      { itemIndex: 7, activityName: 'Labores Culturales', costCategory: 'Labores Culturales', quantity: 9, unit: 'JORNAL', unitCost: 100, totalCost: 900 },
      { itemIndex: 8, activityName: 'Cosecha', costCategory: 'Cosecha', quantity: 12, unit: 'JORNAL', unitCost: 100, totalCost: 1200 },
      { itemIndex: 9, activityName: 'Transporte y Bolsas', costCategory: 'Post Cosecha', quantity: 144, unit: 'CARGA', unitCost: 8, totalCost: 1152 },
      { itemIndex: 10, activityName: 'Otros Gastos', costCategory: 'Varios', quantity: 1, unit: 'GLOBAL', unitCost: 400, totalCost: 400 },
    ],
  },
  {
    cropIndex: 2,
    productName: 'MAÍZ MOROCHO',
    yieldUnit: 'QUINTAL',
    cyclesPerYear: 1,
    cultivatedAreaHectares: 1,
    harvestWasteOrConsumption: 2,
    yieldPerHectare: 125,
    totalYield: 123,
    salePrice: 380,
    totalProductionCost: 9784,
    totalSales: 46740,
    grossMarginPercentage: 0.7907,
    salesMonthlyDistribution: [0.37, 0, 0, 0, 0, 0, 0, 0, 0.05, 0, 0.35, 0.23],
    costsMonthlyDistribution: [0, 0, 0, 0, 0, 0.35, 0.15, 0.15, 0.25, 0, 0.05, 0.05],
    costItems: [
      { itemIndex: 1, activityName: 'Preparación de Terreno', costCategory: 'Mantenimiento', quantity: 4, unit: 'HORA', unitCost: 150, totalCost: 600 },
      { itemIndex: 2, activityName: 'Abono Organico', costCategory: 'Siembra', quantity: 1, unit: 'CAMION', unitCost: 3500, totalCost: 3500 },
      { itemIndex: 3, activityName: 'Abono Quimico', costCategory: 'Insumos', quantity: 2, unit: 'QUINTAL', unitCost: 350, totalCost: 700 },
      { itemIndex: 4, activityName: 'Remedio Quimico en Polvo', costCategory: 'Insumos', quantity: 2, unit: 'KILOGRAMO', unitCost: 350, totalCost: 700 },
      { itemIndex: 5, activityName: 'Remedio Quimico en Liquido', costCategory: 'Insumos', quantity: 2, unit: 'LITRO', unitCost: 350, totalCost: 700 },
      { itemIndex: 6, activityName: 'Semilla de Maiz', costCategory: 'Labores Culturales', quantity: 4, unit: 'ARROBA', unitCost: 150, totalCost: 600 },
      { itemIndex: 7, activityName: 'Mano de Obra Siembra', costCategory: 'Cosecha', quantity: 4, unit: 'JORNAL', unitCost: 100, totalCost: 400 },
      { itemIndex: 8, activityName: 'Mano de Obra Aporque', costCategory: 'Post Cosecha', quantity: 4, unit: 'JORNAL', unitCost: 100, totalCost: 400 },
      { itemIndex: 9, activityName: 'Mano de Obra Cosecha', costCategory: 'Cosecha', quantity: 8, unit: 'JORNAL', unitCost: 100, totalCost: 800 },
      { itemIndex: 10, activityName: 'Comercialización', costCategory: 'Comercialización', quantity: 123, unit: 'QUINTAL', unitCost: 8, totalCost: 984 },
      { itemIndex: 11, activityName: 'Otros Gastos', costCategory: 'Varios', quantity: 1, unit: 'GLOBAL', unitCost: 400, totalCost: 400 },
    ],
  },
  {
    cropIndex: 3,
    productName: 'PAPA MISKA',
    yieldUnit: 'CARGA',
    cyclesPerYear: 1,
    cultivatedAreaHectares: 2,
    harvestWasteOrConsumption: 2,
    yieldPerHectare: 145,
    totalYield: 288,
    salePrice: 250,
    totalProductionCost: 42504,
    totalSales: 72000,
    grossMarginPercentage: 0.4097,
    salesMonthlyDistribution: [0, 0, 0, 0, 0.30, 0.70, 0, 0, 0, 0, 0, 0],
    costsMonthlyDistribution: [0, 0, 0.30, 0.06, 0.30, 0.34, 0, 0, 0, 0, 0, 0],
    costItems: [
      { itemIndex: 1, activityName: 'Preparacion del Terreno', costCategory: 'Mantenimiento', quantity: 8, unit: 'HORA', unitCost: 150, totalCost: 1200 },
      { itemIndex: 2, activityName: 'Siembra', costCategory: 'Siembra', quantity: 20, unit: 'JORNAL', unitCost: 100, totalCost: 2000 },
      { itemIndex: 3, activityName: 'Semilla', costCategory: 'Insumos', quantity: 40, unit: 'CARGA', unitCost: 450, totalCost: 18000 },
      { itemIndex: 4, activityName: 'Abono Quimico', costCategory: 'Insumos', quantity: 12, unit: 'QUINTAL', unitCost: 350, totalCost: 4200 },
      { itemIndex: 5, activityName: 'Abono Organico', costCategory: 'Insumos', quantity: 2, unit: 'CAMION', unitCost: 3500, totalCost: 7000 },
      { itemIndex: 6, activityName: 'Remedios Quimicos', costCategory: 'Labores Culturales', quantity: 8, unit: 'LITRO', unitCost: 350, totalCost: 2800 },
      { itemIndex: 7, activityName: 'Labores Culturales', costCategory: 'Labores Culturales', quantity: 18, unit: 'JORNAL', unitCost: 100, totalCost: 1800 },
      { itemIndex: 8, activityName: 'Cosecha', costCategory: 'Cosecha', quantity: 24, unit: 'JORNAL', unitCost: 100, totalCost: 2400 },
      { itemIndex: 9, activityName: 'Transporte y Bolsas', costCategory: 'Post Cosecha', quantity: 288, unit: 'CARGA', unitCost: 8, totalCost: 2304 },
      { itemIndex: 10, activityName: 'Otros Gastos', costCategory: 'Varios', quantity: 1, unit: 'GLOBAL', unitCost: 800, totalCost: 800 },
    ],
  },
];
