import { Client } from '../types';

export const CLIENTS_DATABASE: Client[] = [
  {
    documentId: '5021899',
    firstSurname: 'CHAVARRIA',
    secondSurname: 'FLORES',
    marriedSurname: 'Vda De. BURGOS',
    firstNames: 'ADELFA',
    idExpirationDate: '2029-09-13',
    maritalStatus: 'VIUDO',
    dependentsCount: 1,
    localitySeniorityMonths: 588,
    activityExperienceMonths: 120,
    educationLevel: 'Primaria',
    housingType: 'Propia',
    businessPremisesType: 'Propia',
    department: 'TARIJA',
    province: 'Aniceto Arce',
    municipality: 'Padcaya',
    locality: 'ABRA DE LA CRUZ',
    infocredRating: 'Calificación 5',
    infocredDate: '2026-07-23',
    economicSector: 'AGRICOLA',
    economicActivityCaedec: 'CULTIVO DE HORTALIZAS DE RAIZ Y TUBERCULO',
    creditHistory: [
      { code: '202400089', amount: 15000, termMonths: 18, status: 'CANCELADO', agency: 'AGENCIA PADCAYA', year: '2024' },
      { code: '202600148', amount: 20000, termMonths: 24, status: 'EN_EVALUACION', agency: 'AGENCIA PADCAYA', year: '2026' },
    ],
  },
  {
    documentId: '3489120',
    firstSurname: 'MAMANI',
    secondSurname: 'CONDORI',
    marriedSurname: '',
    firstNames: 'JUAN CARLOS',
    idExpirationDate: '2028-05-20',
    maritalStatus: 'CASADO',
    dependentsCount: 3,
    localitySeniorityMonths: 240,
    activityExperienceMonths: 96,
    educationLevel: 'Secundaria',
    housingType: 'Propia',
    businessPremisesType: 'Propia',
    department: 'COCHABAMBA',
    province: 'Carrasco',
    municipality: 'Ivirgarzama',
    locality: 'Puerto Villarroel Km 12',
    infocredRating: 'Calificación 5',
    infocredDate: '2026-08-10',
    economicSector: 'AGRICOLA',
    economicActivityCaedec: 'CULTIVO DE FRUTALES Y CITRICOS',
    creditHistory: [
      { code: '202500042', amount: 25000, termMonths: 24, status: 'CANCELADO', agency: 'AGENCIA IVIRGARZAMA', year: '2025' },
    ],
  },
  {
    documentId: '4892301',
    firstSurname: 'GUZMAN',
    secondSurname: 'TORREZ',
    marriedSurname: 'De. SAAVEDRA',
    firstNames: 'ROSARIO',
    idExpirationDate: '2027-11-10',
    maritalStatus: 'CASADO',
    dependentsCount: 2,
    localitySeniorityMonths: 180,
    activityExperienceMonths: 84,
    educationLevel: 'Bachiller',
    housingType: 'Propia',
    businessPremisesType: 'Propia',
    department: 'SANTA CRUZ',
    province: 'Obispo Santistevan',
    municipality: 'Montero',
    locality: 'Guabirá Calle 3',
    infocredRating: 'Calificación 5',
    infocredDate: '2026-06-15',
    economicSector: 'AGRICOLA',
    economicActivityCaedec: 'CULTIVO DE GRANOS Y CEREALES',
    creditHistory: [
      { code: '202300115', amount: 30000, termMonths: 36, status: 'CANCELADO', agency: 'AGENCIA MONTERO', year: '2023' },
    ],
  },
  {
    documentId: '6198432',
    firstSurname: 'QUISPE',
    secondSurname: 'APAZA',
    marriedSurname: '',
    firstNames: 'BERNARDINO',
    idExpirationDate: '2030-04-15',
    maritalStatus: 'CASADO',
    dependentsCount: 2,
    localitySeniorityMonths: 360,
    activityExperienceMonths: 144,
    educationLevel: 'Secundaria',
    housingType: 'Propia',
    businessPremisesType: 'Propia',
    department: 'LA PAZ',
    province: 'Aroma',
    municipality: 'Patacamaya',
    locality: 'Comunidad San Pedro de Curahuara',
    infocredRating: 'Calificación 5',
    infocredDate: '2026-08-25',
    economicSector: 'AGRICOLA',
    economicActivityCaedec: 'CULTIVO DE CEREALES, GRANOS ANDINOS Y TUBERCULOS',
    creditHistory: [
      { code: '202400102', amount: 12000, termMonths: 18, status: 'CANCELADO', agency: 'AGENCIA PATACAMAYA', year: '2024' },
    ],
  },
  {
    documentId: '4582190',
    firstSurname: 'MAMANI',
    secondSurname: 'CHOQUE',
    marriedSurname: '',
    firstNames: 'TEODORO',
    idExpirationDate: '2029-07-18',
    maritalStatus: 'CASADO',
    dependentsCount: 3,
    localitySeniorityMonths: 300,
    activityExperienceMonths: 180,
    educationLevel: 'Secundaria',
    housingType: 'Propia',
    businessPremisesType: 'Propia',
    department: 'COCHABAMBA',
    province: 'Carrasco',
    municipality: 'Puerto Villarroel',
    locality: 'Ivirgarzama - Sindicato San Salvador Senda VI',
    infocredRating: 'Calificación 5',
    infocredDate: '2026-08-30',
    economicSector: 'AGRICOLA',
    economicActivityCaedec: 'CULTIVO DE FRUTAS TROPICALES Y SUBTROPICALES (BANANO Y PIÑA)',
    creditHistory: [
      { code: '202400055', amount: 20000, termMonths: 24, status: 'CANCELADO', agency: 'AGENCIA IVIRGARZAMA', year: '2024' },
      { code: '202600151', amount: 25000, termMonths: 24, status: 'EN_EVALUACION', agency: 'AGENCIA IVIRGARZAMA', year: '2026' },
    ],
  },
];
