export const GEO_DATA: Record<string, Record<string, string[]>> = {
  TARIJA: {
    'Aniceto Arce': ['Padcaya', 'Bermejo'],
    'Cercado': ['Tarija'],
    'Gran Chaco': ['Yacuiba', 'Villamontes', 'Caraparí'],
    'José María Avilés': ['Uriondo (Concepción)', 'Yunchará'],
    'Eustaquio Méndez': ['San Lorenzo', 'El Puente'],
    'Burnet O\'Connor': ['Entre Ríos'],
  },
  CHUQUISACA: {
    'Oropeza': ['Sucre', 'Yotala', 'Poroma'],
    'Nor Cinti': ['Camargo', 'San Lucas', 'Incahuasi', 'Villa Charcas'],
    'Sud Cinti': ['Villa Abecia', 'Culpina', 'Las Carreras'],
    'Hernando Siles': ['Monteagudo', 'Huacareta'],
    'Tomina': ['Padilla', 'Tomina', 'Sopachuy', 'El Villar', 'Villa Serrano'],
    'Zudáñez': ['Zudáñez', 'Presto', 'Mojocoya', 'Icla'],
    'Azurduy': ['Azurduy', 'Tarvita'],
    'Yamparáez': ['Tarabuco', 'Yamparáez'],
    'Luis Calvo': ['Villa Vaca Guzmán', 'Huacaya', 'Macharetí'],
  },
  'LA PAZ': {
    'Murillo': ['La Paz', 'El Alto', 'Palca', 'Mecapaca', 'Achocalla'],
    'Caranavi': ['Caranavi'],
    'Sud Yungas': ['Chulumani', 'Irupana', 'Yanacachi', 'Palos Blancos', 'La Asunta'],
    'Nor Yungas': ['Coroico', 'Coripata'],
    'Loayza': ['Luribay', 'Sapahaqui', 'Yaco', 'Malla', 'Cairoma'],
    'Aroma': ['Patacamaya', 'Sica Sica', 'Umala', 'Ayo Ayo', 'Calamarca'],
    'Abel Iturralde': ['San Buenaventura', 'Ixiamas'],
    'Omasuyos': ['Achacachi', 'Ancoraimes', 'Chua Cocani'],
    'Ingavi': ['Viacha', 'Guaqui', 'Tiwanaku', 'Desaguadero'],
  },
  COCHABAMBA: {
    'Cercado': ['Cochabamba'],
    'Carrasco': ['Ivirgarzama', 'Puerto Villarroel', 'Totora', 'Pojo', 'Entre Ríos'],
    'Chapare': ['Villa Tunari', 'Sacaba', 'Colomi'],
    'Punata': ['Punata', 'San Benito', 'Villa Rivero'],
    'Campero': ['Aiquile', 'Pasorapa', 'Omereque'],
    'Ayopaya': ['Independencia', 'Morochata'],
    'Quillacollo': ['Quillacollo', 'Sipe Sipe', 'Tiquipaya', 'Vinto'],
    'Esteban Arce': ['Tarata', 'Anzaldo', 'Arbieto'],
  },
  'SANTA CRUZ': {
    'Andrés Ibáñez': ['Santa Cruz de la Sierra', 'Cotoca', 'La Guardia', 'El Torno'],
    'Obispo Santistevan': ['Montero', 'Saavedra', 'Mineros', 'Fernández Alonso', 'San Pedro'],
    'Ichilo': ['Yapacaní', 'Buena Vista', 'San Carlos', 'San Juan'],
    'Cordillera': ['Camiri', 'Lagunillas', 'Charagua', 'Cabezas', 'Boyuibe'],
    'Manuel María Caballero': ['Comarapa', 'Saipina'],
    'Florida': ['Mairana', 'Samaipata', 'Pampa Grande'],
    'Ñuflo de Chávez': ['San Julián', 'Concepción', 'San Javier', 'Cuatro Cañadas'],
    'Velasco': ['San Ignacio de Velasco', 'Santa Rosa de Roca', 'San Miguel'],
    'Sara': ['Santa Rosa del Sara', 'Portachuelo', 'Colpa Bélgica'],
    'Chiquitos': ['San José de Chiquitos', 'Pailón', 'Roboré'],
  },
  POTOSI: {
    'Tomás Frías': ['Potosí', 'Yocalla', 'Tinguipaya'],
    'Sud Chichas': ['Tupiza', 'Atocha'],
    'Antonio Quijarro': ['Uyuni', 'Tomave', 'Porco'],
    'Modesto Omiste': ['Villazón'],
    'Nor Chichas': ['Cotagaita', 'Vitichi'],
    'Cornelio Saavedra': ['Betanzos', 'Chaquí'],
    'Chayanta': ['Colquechaca', 'Ravelo', 'Pocoata'],
  },
  ORURO: {
    'Cercado': ['Oruro', 'Caracollo', 'Soracachi'],
    'Ladislao Cabrera': ['Salinas de Garcí Mendoza', 'Pampa Aullagas'],
    'Eduardo Abaroa': ['Challapata', 'Quillacas'],
    'Pantaleón Dalence': ['Huanuni', 'Machacamarca'],
    'Poopó': ['Poopó', 'Pazña'],
  },
  BENI: {
    'Cercado': ['Trinidad', 'San Javier'],
    'Vaca Díez': ['Riberalta', 'Guayaramerín'],
    'José Ballivián': ['Rurrenabaque', 'Reyes', 'San Borja', 'Santa Rosa'],
    'Moxos': ['San Ignacio de Moxos'],
    'Yacuma': ['Santa Ana del Yacuma', 'Exaltación'],
  },
  PANDO: {
    'Nicolás Suárez': ['Cobija', 'Porvenir', 'Bolpebra', 'Bella Flor'],
    'Madre de Dios': ['Puerto Gonzalo Moreno', 'San Lorenzo', 'Sena'],
    'Manuripi': ['Puerto Rico', 'San Pedro', 'Filadelfia'],
  },
};
