import { Solicitud } from '../types';
import { BENCHMARK_CROPS } from './benchmarkCrops';

export const INITIAL_SOLICITUDES: Solicitud[] = [
  {
    id: 'eval-1',
    code: 202600148,
    visitDate: '2026-08-03',
    applicantDocument: '5021899',
    applicantName: 'ADELFA CHAVARRIA FLORES Vda De. BURGOS',
    agency: 'AGENCIA PADCAYA',
    requestedAmount: 20000,
    termMonths: 24,
    paymentFrequency: 'SEMESTRAL',
    interestRate: 11.0,
    creditOfficer: 'Ing. Mariana Ríos (AGENCIA PADCAYA)',
    economicSector: 'AGRICOLA',
    status: 'EN_EVALUACION',
    crops: BENCHMARK_CROPS,
  },
  {
    id: 'eval-2',
    code: 202600149,
    visitDate: '2026-08-15',
    applicantDocument: '3489120',
    applicantName: 'JUAN CARLOS MAMANI CONDORI',
    agency: 'AGENCIA PADCAYA',
    requestedAmount: 14000,
    termMonths: 12,
    paymentFrequency: 'SEMESTRAL',
    interestRate: 11.0,
    creditOfficer: 'Ing. Mariana Ríos (AGENCIA PADCAYA)',
    economicSector: 'AGRICOLA',
    status: 'EN_EVALUACION',
    crops: [
      {
        cropIndex: 1,
        productName: 'CÍTRICOS Y NARANJA',
        yieldUnit: 'CIEN',
        cyclesPerYear: 1,
        cultivatedAreaHectares: 1.5,
        harvestWasteOrConsumption: 5,
        yieldPerHectare: 200,
        totalYield: 295,
        salePrice: 80,
        totalProductionCost: 11800,
        totalSales: 23600,
        grossMarginPercentage: 0.50,
        salesMonthlyDistribution: [0, 0, 0, 0, 0, 0.4, 0.6, 0, 0, 0, 0, 0],
        costsMonthlyDistribution: [0.2, 0.3, 0.3, 0.2, 0, 0, 0, 0, 0, 0, 0, 0],
        costItems: [
          { itemIndex: 1, activityName: 'Mantenimiento de Huerto', costCategory: 'Mantenimiento', quantity: 10, unit: 'JORNAL', unitCost: 100, totalCost: 1000 },
          { itemIndex: 2, activityName: 'Abonado y Fertilización', costCategory: 'Insumos', quantity: 8, unit: 'QUINTAL', unitCost: 350, totalCost: 2800 },
          { itemIndex: 3, activityName: 'Control Fitosanitario', costCategory: 'Labores Culturales', quantity: 6, unit: 'LITRO', unitCost: 350, totalCost: 2100 },
          { itemIndex: 4, activityName: 'Cosecha y Selección', costCategory: 'Cosecha', quantity: 35, unit: 'JORNAL', unitCost: 100, totalCost: 3500 },
          { itemIndex: 5, activityName: 'Transporte y Embalaje', costCategory: 'Post Cosecha', quantity: 295, unit: 'CIEN', unitCost: 8, totalCost: 2400 },
        ],
      },
    ],
  },
  {
    id: 'eval-3',
    code: 202600147,
    visitDate: '2026-07-10',
    applicantDocument: '4892301',
    applicantName: 'ROSARIO GUZMAN TORREZ De. SAAVEDRA',
    agency: 'AGENCIA MONTERO',
    requestedAmount: 35000,
    termMonths: 36,
    paymentFrequency: 'SEMESTRAL',
    interestRate: 11.5,
    creditOfficer: 'Lic. Roberto Gómez (AGENCIA MONTERO)',
    economicSector: 'AGRICOLA',
    status: 'APROBADO',
    crops: [
      {
        cropIndex: 1,
        productName: 'SOYA DE VERANO',
        yieldUnit: 'TONELADA',
        cyclesPerYear: 1,
        cultivatedAreaHectares: 5,
        harvestWasteOrConsumption: 0,
        yieldPerHectare: 2.5,
        totalYield: 12.5,
        salePrice: 2800,
        totalProductionCost: 18500,
        totalSales: 35000,
        grossMarginPercentage: 0.4714,
        salesMonthlyDistribution: [0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0, 0],
        costsMonthlyDistribution: [0.3, 0.4, 0.3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        costItems: [
          { itemIndex: 1, activityName: 'Preparación de Suelo', costCategory: 'Mantenimiento', quantity: 15, unit: 'HORA', unitCost: 200, totalCost: 3000 },
          { itemIndex: 2, activityName: 'Semilla Certificada', costCategory: 'Insumos', quantity: 10, unit: 'BOLSA', unitCost: 450, totalCost: 4500 },
          { itemIndex: 3, activityName: 'Herbicidas y Defensivos', costCategory: 'Labores Culturales', quantity: 10, unit: 'LITRO', unitCost: 350, totalCost: 3500 },
          { itemIndex: 4, activityName: 'Cosecha Mecanizada', costCategory: 'Cosecha', quantity: 5, unit: 'HECTAREA', unitCost: 1000, totalCost: 5000 },
          { itemIndex: 5, activityName: 'Flete a Acopio', costCategory: 'Post Cosecha', quantity: 12.5, unit: 'TONELADA', unitCost: 200, totalCost: 2500 },
        ],
      },
    ],
  },
  {
    id: 'eval-4',
    code: 202600150,
    visitDate: '2026-08-25',
    applicantDocument: '6198432',
    applicantName: 'BERNARDINO QUISPE APAZA',
    agency: 'AGENCIA PATACAMAYA',
    requestedAmount: 18000,
    termMonths: 24,
    paymentFrequency: 'SEMESTRAL',
    interestRate: 11.0,
    creditOfficer: 'Lic. Carlos Mendoza (AGENCIA PATACAMAYA)',
    economicSector: 'AGRICOLA',
    status: 'EN_EVALUACION',
    crops: [
      {
        cropIndex: 1,
        productName: 'QUINUA REAL BLANCA',
        yieldUnit: 'QUINTAL',
        cyclesPerYear: 1,
        cultivatedAreaHectares: 2,
        harvestWasteOrConsumption: 2,
        yieldPerHectare: 25,
        totalYield: 48,
        salePrice: 480,
        totalProductionCost: 9600,
        totalSales: 23040,
        grossMarginPercentage: 0.5833,
        salesMonthlyDistribution: [0, 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0],
        costsMonthlyDistribution: [0, 0.2, 0.3, 0.3, 0.2, 0, 0, 0, 0, 0, 0, 0],
        costItems: [
          { itemIndex: 1, activityName: 'Barbecho y Preparación de Suelo', costCategory: 'Mantenimiento', quantity: 6, unit: 'HORA', unitCost: 180, totalCost: 1080 },
          { itemIndex: 2, activityName: 'Siembra Mecanizada', costCategory: 'Siembra', quantity: 4, unit: 'HORA', unitCost: 180, totalCost: 720 },
          { itemIndex: 3, activityName: 'Semilla de Quinua Certificada', costCategory: 'Insumos', quantity: 20, unit: 'KILOGRAMO', unitCost: 45, totalCost: 900 },
          { itemIndex: 4, activityName: 'Abono Estiércol Ovino Tratado', costCategory: 'Insumos', quantity: 1, unit: 'CAMION', unitCost: 2500, totalCost: 2500 },
          { itemIndex: 5, activityName: 'Control Biológico y Bioinsumos', costCategory: 'Labores Culturales', quantity: 1, unit: 'GLOBAL', unitCost: 900, totalCost: 900 },
          { itemIndex: 6, activityName: 'Corte y Emparvado', costCategory: 'Cosecha', quantity: 15, unit: 'JORNAL', unitCost: 100, totalCost: 1500 },
          { itemIndex: 7, activityName: 'Trilla Mecanizada', costCategory: 'Cosecha', quantity: 5, unit: 'HORA', unitCost: 200, totalCost: 1000 },
          { itemIndex: 8, activityName: 'Venteo y Embolsado', costCategory: 'Post Cosecha', quantity: 48, unit: 'QUINTAL', unitCost: 15, totalCost: 720 },
          { itemIndex: 9, activityName: 'Transporte a Centro de Acopio', costCategory: 'Post Cosecha', quantity: 1, unit: 'GLOBAL', unitCost: 280, totalCost: 280 },
        ],
      },
      {
        cropIndex: 2,
        productName: 'PAPA HUAYCHA DEL ALTIPLANO',
        yieldUnit: 'CARGA',
        cyclesPerYear: 1,
        cultivatedAreaHectares: 1,
        harvestWasteOrConsumption: 1,
        yieldPerHectare: 110,
        totalYield: 109,
        salePrice: 220,
        totalProductionCost: 11400,
        totalSales: 23980,
        grossMarginPercentage: 0.5246,
        salesMonthlyDistribution: [0, 0, 0, 0, 0, 0, 0.4, 0.6, 0, 0, 0, 0],
        costsMonthlyDistribution: [0, 0.15, 0.35, 0.3, 0.2, 0, 0, 0, 0, 0, 0, 0],
        costItems: [
          { itemIndex: 1, activityName: 'Preparación del Suelo', costCategory: 'Mantenimiento', quantity: 4, unit: 'HORA', unitCost: 180, totalCost: 720 },
          { itemIndex: 2, activityName: 'Siembra', costCategory: 'Siembra', quantity: 10, unit: 'JORNAL', unitCost: 100, totalCost: 1000 },
          { itemIndex: 3, activityName: 'Semilla de Papa Huaycha', costCategory: 'Insumos', quantity: 12, unit: 'CARGA', unitCost: 400, totalCost: 4800 },
          { itemIndex: 4, activityName: 'Abono Orgánico y Fitoestimulantes', costCategory: 'Insumos', quantity: 1, unit: 'GLOBAL', unitCost: 1800, totalCost: 1800 },
          { itemIndex: 5, activityName: 'Aporque y Deshierbe', costCategory: 'Labores Culturales', quantity: 8, unit: 'JORNAL', unitCost: 100, totalCost: 800 },
          { itemIndex: 6, activityName: 'Cosecha y Selección', costCategory: 'Cosecha', quantity: 14, unit: 'JORNAL', unitCost: 100, totalCost: 1400 },
          { itemIndex: 7, activityName: 'Transporte y Sacos', costCategory: 'Post Cosecha', quantity: 109, unit: 'CARGA', unitCost: 8, totalCost: 872 },
          { itemIndex: 8, activityName: 'Otros Gastos Operativos', costCategory: 'Varios', quantity: 1, unit: 'GLOBAL', unitCost: 8, totalCost: 8 },
        ],
      },
    ],
  },
  {
    id: 'eval-5',
    code: 202600151,
    visitDate: '2026-08-30',
    applicantDocument: '4582190',
    applicantName: 'TEODORO MAMANI CHOQUE',
    agency: 'AGENCIA IVIRGARZAMA',
    requestedAmount: 25000,
    termMonths: 24,
    paymentFrequency: 'SEMESTRAL',
    interestRate: 11.0,
    creditOfficer: 'Ing. Marcelo Fernández (AGENCIA IVIRGARZAMA)',
    economicSector: 'AGRICOLA',
    status: 'EN_EVALUACION',
    crops: [
      {
        cropIndex: 1,
        productName: 'BANANO DE EXPORTACIÓN CAVENDISH',
        yieldUnit: 'CAJA (19.5 KG)',
        cyclesPerYear: 1,
        cultivatedAreaHectares: 2,
        harvestWasteOrConsumption: 80,
        yieldPerHectare: 1180,
        totalYield: 2280,
        salePrice: 32,
        totalProductionCost: 32400,
        totalSales: 72960,
        grossMarginPercentage: 0.5559,
        salesMonthlyDistribution: [0.08, 0.08, 0.08, 0.08, 0.08, 0.09, 0.09, 0.09, 0.09, 0.08, 0.08, 0.08],
        costsMonthlyDistribution: [0.1, 0.1, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08, 0.08],
        costItems: [
          { itemIndex: 1, activityName: 'Limpieza, Deshierbe y Plateo', costCategory: 'Mantenimiento', quantity: 16, unit: 'JORNAL', unitCost: 100, totalCost: 1600 },
          { itemIndex: 2, activityName: 'Deshoje Fitosanitario y Control de Sigatoka', costCategory: 'Labores Culturales', quantity: 14, unit: 'JORNAL', unitCost: 100, totalCost: 1400 },
          { itemIndex: 3, activityName: 'Fertilizantes (Urea + Cloruro de Potasio)', costCategory: 'Insumos', quantity: 20, unit: 'QUINTAL', unitCost: 350, totalCost: 7000 },
          { itemIndex: 4, activityName: 'Fundas de Protección y Cinta de Identificación', costCategory: 'Insumos', quantity: 2300, unit: 'UNIDAD', unitCost: 1.80, totalCost: 4140 },
          { itemIndex: 5, activityName: 'Deschante, Apuntalado y Amarre de Plantas', costCategory: 'Labores Culturales', quantity: 12, unit: 'JORNAL', unitCost: 100, totalCost: 1200 },
          { itemIndex: 6, activityName: 'Cosecha, Desmane y Lavado en Tina', costCategory: 'Cosecha', quantity: 80, unit: 'JORNAL', unitCost: 100, totalCost: 8000 },
          { itemIndex: 7, activityName: 'Cajas de Cartón Exportación y Flete a Empacadora', costCategory: 'Post Cosecha', quantity: 2280, unit: 'CAJA', unitCost: 3.9736, totalCost: 9060 },
        ],
      },
      {
        cropIndex: 2,
        productName: 'PIÑA TROPICAL GOLD (MD2)',
        yieldUnit: 'CAJA (12 KG)',
        cyclesPerYear: 1,
        cultivatedAreaHectares: 1,
        harvestWasteOrConsumption: 20,
        yieldPerHectare: 850,
        totalYield: 830,
        salePrice: 35,
        totalProductionCost: 11800,
        totalSales: 29050,
        grossMarginPercentage: 0.5938,
        salesMonthlyDistribution: [0, 0, 0, 0, 0, 0, 0.2, 0.4, 0.4, 0, 0, 0],
        costsMonthlyDistribution: [0.35, 0.25, 0.15, 0.1, 0.05, 0.05, 0.05, 0, 0, 0, 0, 0],
        costItems: [
          { itemIndex: 1, activityName: 'Preparación de Suelo y Camellones', costCategory: 'Mantenimiento', quantity: 8, unit: 'HORA', unitCost: 200, totalCost: 1600 },
          { itemIndex: 2, activityName: 'Hijuelos Seleccionados de Piña Golden MD2', costCategory: 'Insumos', quantity: 12000, unit: 'UNIDAD', unitCost: 0.40, totalCost: 4800 },
          { itemIndex: 3, activityName: 'Fertilización Foliar y Nutrición NPK', costCategory: 'Insumos', quantity: 6, unit: 'QUINTAL', unitCost: 350, totalCost: 2100 },
          { itemIndex: 4, activityName: 'Deshierbe y Cuidados Culturales', costCategory: 'Labores Culturales', quantity: 10, unit: 'JORNAL', unitCost: 100, totalCost: 1000 },
          { itemIndex: 5, activityName: 'Inducción Floral y Protección Solar', costCategory: 'Labores Culturales', quantity: 1, unit: 'GLOBAL', unitCost: 800, totalCost: 800 },
          { itemIndex: 6, activityName: 'Cosecha, Selección y Encanastillado', costCategory: 'Cosecha', quantity: 15, unit: 'JORNAL', unitCost: 100, totalCost: 1500 },
        ],
      },
    ],
  },
];
